In [1]:
import numpy as np
def softmax(x):
    if x.ndim == 1:
        x -= np.min(x)
        x = np.exp(x)
        x /= np.sum(x)
    else:
        x -= np.min(x, axis = 1, keepdims = True)
        x = np.exp(x)
        x /= np.sum(x, axis = 1, keepdims = True)
    return x

In [2]:
a = np.array([2,3,5])
a = softmax(a)
print a

a = np.array([[2,3,5], [1,2,4]])
a = softmax(a)
print a

[ 0.04201007  0.1141952   0.84379473]
[[ 0.04201007  0.1141952   0.84379473]
 [ 0.04201007  0.1141952   0.84379473]]
