In [1]:
import numpy as np
import random

In [2]:
# First implement a gradient checker by filling in the following functions
def gradcheck_naive(f, x):
    """ 
    Gradient check for a function f 
    - f should be a function that takes a single argument and outputs the cost and its gradients
    - x is the point (numpy array) to check the gradient at
    """ 

    rndstate = random.getstate()
    random.setstate(rndstate)  
    fx, grad = f(x) # Evaluate function value at original point
    h = 1e-4

    # Iterate over all indexes in x
    it = np.nditer(x, flags=['multi_index'], op_flags=['readwrite'])
    while not it.finished:
        ix = it.multi_index
    
        ### YOUR CODE HERE: try modifying x[ix] with h defined above to compute numerical gradients
        ### make sure you call random.setstate(rndstate) before calling f(x) each time, this will make it 
        ### possible to test cost functions with built in randomness later
        x[ix] += h 
        print x
        random.setstate(rndstate)
        fxph = f(x)[0]
        print fxph
        x[ix] -= 2 * h
        random.setstate(rndstate)
        fxmh = f(x)[0]
        print fxmh
        x[ix] += h
        numgrad = (fxph - fxmh) / (2 * h)  
        print numgrad
        # Compare gradients
        reldiff = abs(numgrad - grad[ix]) / max(1, abs(numgrad), abs(grad[ix]))
        if reldiff > 1e-5:
            print "Gradient check failed."
            print "First gradient error found at index %s" % str(ix)
            print "Your gradient: %f \t Numerical gradient: %f" % (grad[ix], numgrad)
            return
    
        it.iternext() # Step to next dimension

    print "Gradient check passed!"

In [3]:
# Sanity check for the gradient checker

quad = lambda x: (np.sum(x ** 2), x * 2)
print "=== For autograder ==="
gradcheck_naive(quad, np.array(123.456)) # scalar test
gradcheck_naive(quad, np.random.randn(3,)) #1D test
gradcheck_naive(quad, np.random.randn(4,5))   # 2-D test

=== For autograder ===
123.4561
15241.4086272
15241.3592448
246.912000002
Gradient check passed!
[ 0.61832576  0.63619135 -0.05474825]
0.790063542386
0.789816252083
1.23645151481
[ 0.61822576  0.63629135 -0.05474825]
0.790067135504
0.789812658965
1.27238269326
[ 0.61822576  0.63619135 -0.05464825]
0.789928947585
0.789950846884
-0.109496494756
Gradient check passed!
[[ 0.58262728 -1.39813138 -1.92902877 -0.62463352 -0.0252721 ]
 [ 0.029489   -0.39695149 -0.56407286  0.42295565  0.05217776]
 [-0.11754271 -0.89813255  1.29182578  1.10006888 -0.25764087]
 [ 0.28551048  0.62556249 -0.62225374  0.35820966  0.98268538]]
12.7842475928
12.7840145819
1.1650545659
[[ 0.58252728 -1.39803138 -1.92902877 -0.62463352 -0.0252721 ]
 [ 0.029489   -0.39695149 -0.56407286  0.42295565  0.05217776]
 [-0.11754271 -0.89813255  1.29182578  1.10006888 -0.25764087]
 [ 0.28551048  0.62556249 -0.62225374  0.35820966  0.98268538]]
12.7838514611
12.7844107137
-2.79626276948
[[ 0.58252728 -1.39813138 -1.92892877 -0.6