In [ ]:
import numpy as np
import pandas as pd

In [2]:
N = 5
D = 2

X = np.random.randn(N, D)
ones = np.array([[1] * N]).T
Xb = np.concatenate((ones, X), axis=1)

W = np.random.randn(D + 1)

Z = Xb.dot(W)

In [3]:
def sigmoid(z):
    return (1/(1+ np.exp(-z)))

## sigmoid(Z)

In [4]:
def get_data():
    df = pd.read_csv('ecommerce_data.csv')
    data = df.as_matrix()
    print df.head()
    X = data[:, : -1]
    Y = data[:, -1] 
    
    X[:, 1] = (X[:,1] - X[:,1].mean()) / X[:,1].std()
    X[:, 2] = (X[:,2] - X[:,2].mean()) / X[:,2].std()
    
    N, D = X.shape
    X2 = np.zeros((N, D+3))
    X2[:, : D-1] = X[:, : D-1]
    
    for n in xrange(N):
        t = X[n, D-1]
        X2[n, t+ D-1] = 1
    
    #print X2
    
    Z = np.zeros((N, 4))
    Z[np.arange(N), X[:, D-1].astype(np.int32)] = 1
    #print Z
    
    assert(np.abs(X2[:, -4:] - Z).sum() < 10e-10)
    return X2, Y

def get_binary_data():
    X, Y = get_data()
    X2 = X[Y <= 1]
    Y2 = Y[Y <= 1]
    return X2, Y2

In [5]:
X, Y = get_binary_data()
D = X.shape[1]
print "Weights are : %d" %D
W = np.random.randn(D)
b = 0

def forward(X, W, b):
    return sigmoid(np.dot(X, W) + b)

P_Y_givenX = forward(X, W, b)

round_pred = np.round(P_Y_givenX)

print Y == round_pred
def classifier_rate(Y, P):
    return np.mean(Y == P)

print classifier_rate(Y, round_pred)

   is_mobile  n_products_viewed  visit_duration  is_returning_visitor  \
0          1                  0        0.657510                     0   
1          1                  1        0.568571                     0   
2          1                  0        0.042246                     1   
3          1                  1        1.659793                     1   
4          0                  1        2.014745                     1   

   time_of_day  user_action  
0            3            0  
1            2            1  
2            1            0  
3            1            2  
4            1            2  
Weights are : 8
[False  True  True  True False False False False False  True False  True
 False False False False False False  True  True False False False False
 False False False False False  True False  True False  True  True  True
  True  True  True False  True  True  True False False False False False
  True  True False False False False  True False False  True False  True


/Library/Python/2.7/site-packages/ipykernel/__main__.py:17: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future


In [6]:
def cross_entropy_total_error(T, Y):
    error = 0
    N = T.shape[0]
    for i in xrange(N):
        if (T[i] == 1):
            error -= T[i] * np.log(Y[i])
        else:
            error -= (1- T[i]) * np.log(1- Y[i])
    return error

In [7]:
## Comput Cross- Entropy cost
N = 100
D = 2

X = np.random.randn(N, D)
X[: 50, :] = X[: 50, :] - 2 * np.ones((50, D))
X[50: , :] = X[50: , :] + 2 * np.ones((50, D))

T = np.array([1] * 50 + [0] * 50)
ones = np.array([[1] * N]).T

Xb = np.concatenate((ones, X), axis=1)

W = np.random.randn(D + 1)

Z = Xb.dot(W)

Y = sigmoid(Z)

print cross_entropy_total_error(T, Y)

11.5948976096


In [8]:
# Visualize the data
import matplotlib.pyplot as plt

plt.scatter(X[:, 0], X[:, 1], c=T, s=50, alpha = 0.5)
x_axis = np.linspace(-6, 6, 200)
y_axis = x_axis
plt.plot(x_axis, y_axis)
#plt.show()

In [9]:
learning_rate = 0.1
reg_lambda = 0.1
for i in xrange(100):
    error = cross_entropy_total_error(T, Y)
    if (i%10 == 0):
        print error
        print W
    
    W += learning_rate * Xb.T.dot(Y - T) - reg_lambda * W
    Z = Xb.dot(W)
    Y = sigmoid(Z)
    
print "Final W: ", W

11.5948976096
[-0.59886753 -0.52596294 -0.75809791]
inf
[  -0.57425081  127.52894875  125.44852899]
inf
[  -0.20022888  179.82902822  177.17889253]
inf
[ -6.98154929e-02   1.98064938e+02   1.95216155e+02]
inf
[ -2.43431572e-02   2.04423407e+02   2.01505360e+02]
inf
[ -8.48793407e-03   2.06640468e+02   2.03698270e+02]
inf
[ -2.95955961e-03   2.07413509e+02   2.04462890e+02]
inf
[ -1.03193463e-03   2.07683052e+02   2.04729497e+02]
inf
[ -3.59813356e-04   2.07777036e+02   2.04822457e+02]
inf
[ -1.25459160e-04   2.07809806e+02   2.04854870e+02]
Final W:  [ -4.37449042e-05   2.07821232e+02   2.04866172e+02]


/Library/Python/2.7/site-packages/ipykernel/__main__.py:8: RuntimeWarning: divide by zero encountered in log
/Library/Python/2.7/site-packages/ipykernel/__main__.py:2: RuntimeWarning: overflow encountered in exp
  from ipykernel import kernelapp as app
/Library/Python/2.7/site-packages/ipykernel/__main__.py:6: RuntimeWarning: divide by zero encountered in log
